### PR TITLE
code improvment

### LINKED ISSUE #18: Use ‘decimal’ in Python for Correct Precision
From https://www.hl7.org/fhir/datatypes.html#primitive:
> The precision of the decimal value has significance:
e.g. 0.010 is regarded as different to 0.01, and the original precision should be preserved
Implementations SHALL handle decimal values in ways that preserve and respect the precision of the value as represented for presentation purposes
Implementations are not required to perform calculations with these numbers differently, though they may choose to do so (i.e. preserve significance)
See implementation comments for XML, JSON and RDF
In object code, implementations that might meet this constraint are GMP implementations or equivalents to Java BigDecimal that implement arbitrary precision, or a combination of a (64 bit) floating point value with a precision field
Note that large and/or highly precise values are extremely rare in medicine. One element where highly precise decimals may be encountered is the Location coordinates. Irrespective of this, the limits documented in XML Schema apply

To be compliant we need to use [decimal](https://docs.python.org/3.8/library/decimal.html) in Python.

Pydentic seems to support [this](https://pydantic-docs.helpmanual.io/usage/types/).

### LINKED ISSUE #19: Docstrings for enums
ATM we have docstrings for enums, but they are not quite nice.

Some investigation is probalby needed how to do that in the correct way, so the schema generation of pydantic also recognizes the docstrings. What I found is:

https://stackoverflow.com/questions/52062831/how-do-i-properly-document-python-enum-elements

### PR DESCRIPTION
**Pull request by behzadmehrabi**

### CODE REVIEW

**Comment by julian-r** [comment]
Nice Work! The codecov bot is complaining here, that means you could add an unittest to increase coverage. 

Some description of the PR would be nice as well! :)

**Comment by behzadmehrabi** [comment]
[Docstrings recognition added For Enums](https://github.com/skalarsystems/fhirzeug/issues/19)

I change the way *Pydantic* actually shows enums in schema,
so for example instead of being:

` 'enum': [
    'MALE', 
    'FEMALE', 
    'OTHER']
`

it's a key value pair of **value(enum Value)** and **description(enum docstring)**:
```
'enum': [{'value': 'MALE', 'description': 'it is Male docstring'}, {'value': 'FEMALE', 'description': 'it is female docstring'},{'value': 'OTHER', 'description': 'An enumeration.'}]`
```

**NOTE:**

- there's seems like to be an special case, class *TimingRepeat*, which has an extra Items key.
  Enum Key is accessible via:

          `schema["properties"]["dayOfWeek"]["items"]["enum"]`

      instead of:

          `schema["properties"]["dayOfWeek"]["enum"]`


- for now I just wrote a condition for that specific case in *resource.py.jinja2*.

- right now for testing purposes you should Delete one of the Quantity classes manually.([Quantity generated twice](https://github.com/skalarsystems/fhirzeug/issues/16))

*****************
I also Changed _writable_classes_ and _writable_profiles_ 

so instead of:

 ```
 profiles = []
 for key, profile in self.profiles.items():
        if profile.manual_module is None:
            profiles.append(profile)
 return profiles
```

it's:
```
return [profile for profile in self.profiles.values() 
        if profile.manual_module is None]
```

**Comment by behzadmehrabi** [comment]
DocEnum no value assign fixed.

the problem was that I didn't pass the value to `__new__` as a second argument.

*************************

use decimal instead of float for correct precision.

**Comment by behzadmehrabi** [comment]
I hate that bot :))))

**Comment by behzadmehrabi** [comment]
can you help me pass that codecov? =)))

**Comment by julian-r** [comment]
Yes, we need to test lines which are not covered yet. So if you for example https://codecov.io/gh/skalarsystems/fhirzeug/pull/15/src/fhirzeug/fhirrenderer.py?before=fhirzeug/fhirrenderer.py remove the Dependency renderer it will get better

**Comment by Wauplin** [comment]
Hey @Bezmehrabi !
I'm started to work on this project within Skalar and I'd like to help on this pull request, namely for the test coverage. May I ask you to grant me access to your branch so that I can add more unit tests ? (Github doc : https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork ). Thanks !
I might have questions on the code but I'll let you know.

**Comment by Wauplin** [comment]
PR also related to https://github.com/skalarsystems/fhirzeug/issues/18

**Comment by behzadmehrabi** [comment]
Hi @Wauplin , I already checked **Allow edits by maintainers**. should I do something else?

**Comment by Wauplin** [comment]
Hi, thanks for your quick reply. I wasn't maintainer of the project yet. Now it's good. :+1:

**Comment by Wauplin** [comment]
I have added a new test to your PR so that it passes codecov check. It's not by far but it's enough :slightly_smiling_face:

**Pull request merged**
